# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - test-37:
          filters:
            tags:
              only: /.*/
      - test-36:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test-37
            - test-36
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

commands:
  setup:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
      - run:
          name: install dependencies
          command: |
            python --version
            virtualenv venv
            . venv/bin/activate;
            pip install -e .;
            pip install -e .[dev]
      - save_cache:
          paths:
            - ./venv
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}

jobs:
  test-37: &test-template
    docker:
      - image: circleci/python:3.7
    working_directory: ~/pytest-opentmi
    steps:
      - setup
      # run tests!
      - run:
          name: unit tests
          command: |
            mkdir junit || true
            . venv/bin/activate;
            nosetests --with-xunit --with-coverage --cover-package=pytest_opentmi --cover-html --cover-html-dir=htmlcov --cover-xml-file=coverage.xml --xunit-file=junit/results.xml
            coveralls || true
      - run:
          name: pylint
          command: |
            . venv/bin/activate;
            pylint pytest_opentmi
      - run:
          name: run
          command: |
            . venv/bin/activate;
            cd example;
            pytest --opentmi localhost:3000 --opentmi_token 123 --metadata foo bar --metadata DUT_SERIAL_NUMBER 123 --metadata DUT_MODEL S5 --metadata DUT_VENDOR samsang example.py
      - store_artifacts:
          path: htmlcov
          destination: htmlcov
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit
          destination: juni

  test-36:
    <<: *test-template
    docker:
    - image: circleci/python:3.6

  deploy:
    <<: *test-template
    steps:
      - setup
      - run:
          name: create packages
          command: |
            . venv/bin/activate;
            python setup.py sdist
            python setup.py bdist_wheel
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate;
            pip install twine;
            export PATH=$HOME/.local/bin:$PATH;
            twine upload dist/*
